// generated by stringer -type=ParityMode,FlowMode -output enum_strings.go; DO NOT EDIT

package serial

import "fmt"

const _ParityMode_name = "ParityNoneParityEvenParityOddParityMarkParitySpace"

var _ParityMode_index = [...]uint8{0, 10, 20, 29, 39, 50}

func (i ParityMode) String() string {
	if i < 0 || i >= ParityMode(len(_ParityMode_index)-1) {
		return fmt.Sprintf("ParityMode(%d)", i)
	}
	return _ParityMode_name[_ParityMode_index[i]:_ParityMode_index[i+1]]
}

const _FlowMode_name = "FlowNoneFlowRTSCTSFlowXONXOFFFlowOther"

var _FlowMode_index = [...]uint8{0, 8, 18, 29, 38}

func (i FlowMode) String() string {
	if i < 0 || i >= FlowMode(len(_FlowMode_index)-1) {
		return fmt.Sprintf("FlowMode(%d)", i)
	}
	return _FlowMode_name[_FlowMode_index[i]:_FlowMode_index[i+1]]
}
